# Generated by Django 2.0.4 on 2018-04-19 07:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('nickname', models.CharField(max_length=50, unique=True, verbose_name='昵称')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('sex', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=2, verbose_name='性别')),
                ('email', models.CharField(blank=True, max_length=30, null=True, verbose_name='email')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime(2018, 4, 19, 7, 21, 43, 700202, tzinfo=utc), verbose_name='更新时间')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
